INSERT INTO products (name, description, price, stock_quantity, image_url) VALUES 
('Backpack', 'Water resistant', 35, 90, 'backpack.png'),
('Ballpens', 'Gel ink black', 10, 400, 'ballpen.png'), 
('Bluetooth Speaker', 'Portable waterproof', 45, 60, 'bluetooth_speaker.png'), 
('Coffee Mug', 'Ceramic 16oz', 12, 150, 'coffee_mug.png'), 
('Desk Lamp', 'LED dimmable', 22, 50, 'desk_lamp.png'), 
('Dumbbells', '10lb pair', 40, 80, 'dumbbells.jpg'), 
('Earbuds', 'Wireless in-ear', 55, 80, 'earbuds.png'), 
('Flash Drive', '64GB USB 3.0', 18, 150, 'flash_drive.jpg'), 
('HDMI Cable', '4K ultra HD 6ft', 10, 200, 'hdmi_cable.png'), 
('Headset', 'Noise cancelling', 60, 60, 'headset.jpg'), 
('Highlighter', 'Assorted colors', 15, 200, 'highlighter.png'), 
('Laptop Stand', 'Ergonomic aluminum', 30, 40, 'laptop_stand.png'), 
('Mechanical Keyboard', 'Clicky switches', 80, 50, 'mechanical_keyboard.png'), 
('Microphone', 'USB condenser', 65, 45, 'microphone.png'),
('Monitor 24', '1080p 144Hz monitor', 150, 40, 'monitor_24.png'), 
('Mouse', 'The best gaming mouse', 20, 120, 'mouse.png'),
('Notebook', 'Lined 200 pages', 8, 300, 'notebook.jpg'), 
('Office Chair', 'Ergonomic mesh', 150, 20, 'office_chair.jpg'), 
('Power Bank', '10000mAh', 30, 100, 'power_bank.jpg'), 
('Running Shoes', 'Comfortable sneakers', 85, 30, 'running_shoes.jpg'), 
('Smart Watch', 'Fitness tracker', 120, 40, 'smartwatch.png'), 
('Tablet Sleeve', '13 inch protective', 15, 120, 'tablet_sleeve.jpg'), 
('USB-C Cable', '6ft braided', 12, 250, 'usbc_cable.png'), 
('Wall Adapter', 'Dual USB ports', 18, 150, 'wall_adapter.png'), 
('Water Bottle', 'Insulated 32oz', 20, 200, 'water_bottle.png'), 
('Webcam', '1080p with privacy cover', 40, 60, 'webcam.jpg'), 
('Wireless Charger', 'Fast charging pad', 25, 75, 'wireless_charger.png'), 
('Yoga Mat', 'Non-slip eco-friendly mat', 25, 100, 'yoga_mat.png');
